networks:
  ecommerce-net:
    driver: bridge

services:
  eureka-server:
    build:
      context: ./eureka-server/eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - ecommerce-net
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    build:
      context: ./api-gateway/api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8090:8090"
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - ecommerce-net
    restart: on-failure

  product-service:
    build:
      context: ./product-service/product-service
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8081:8081"
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - ecommerce-net
    restart: on-failure

  order-service:
    build:
      context: ./order-service/order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8079:8079"
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - ecommerce-net
    restart: on-failure

  inventory-service:
    build:
      context: ./inventory-service/inventory-service
      dockerfile: Dockerfile
    container_name: inventory-service
    ports:
      - "8083:8083"
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - ecommerce-net
    restart: on-failure

  payment-service:
    build:
      context: ./payment-service/payment-service
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - "8084:8084"
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - ecommerce-net
    restart: on-failure
