name: Deploy to EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY2 }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST2 }} >> ~/.ssh/known_hosts

      - name: Connect & Deploy
        run: |
          ssh ${{ secrets.EC2_USER2 }}@${{ secrets.EC2_HOST2 }} << 'EOF'
            cd ${{ secrets.EC2_PATH }}
            git pull origin main
            docker-compose down
            docker-compose up --build -d
          EOF

#Ce workflow automatise le déploiement sur ta machine EC2 :
  #Dès que tu pousses du code sur main
  #GitHub Actions se connecte par SSH à ton serveur EC2
  #Récupère les dernières modifications de code
  #Redémarre tes conteneurs Docker pour que la nouvelle version soit active


